// source: Message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Msg_pb = require('./Msg_pb.js');
goog.object.extend(proto, Msg_pb);
var Connection_pb = require('./Connection_pb.js');
goog.object.extend(proto, Connection_pb);
var Team_pb = require('./Team_pb.js');
goog.object.extend(proto, Team_pb);
goog.exportSymbol('proto.Message', null, global);
goog.exportSymbol('proto.Message.PayloadCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Message.oneofGroups_);
};
goog.inherits(proto.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Message.displayName = 'proto.Message';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Message.oneofGroups_ = [[11,12,13,14,15,21,22,51,52,53,54]];

/**
 * @enum {number}
 */
proto.Message.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  AUTH: 11,
  AUTH_ACK: 12,
  PING: 13,
  PONG: 14,
  DISCONNECT: 15,
  MSG_DATA: 21,
  MSG_DATA_ACK: 22,
  CREATE_TEAM_REQ: 51,
  DISMISS_TEAM_REQ: 52,
  QUERY_MEMBER_LIST_REQ: 53,
  JOIN_TEAM_REQ: 54
};

/**
 * @return {proto.Message.PayloadCase}
 */
proto.Message.prototype.getPayloadCase = function() {
  return /** @type {proto.Message.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.Message.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    magic: jspb.Message.getFieldWithDefault(msg, 1, 0),
    version: jspb.Message.getFieldWithDefault(msg, 2, 0),
    opcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    seq: jspb.Message.getFieldWithDefault(msg, 4, 0),
    payloadlength: jspb.Message.getFieldWithDefault(msg, 5, 0),
    auth: (f = msg.getAuth()) && Connection_pb.Auth.toObject(includeInstance, f),
    authAck: (f = msg.getAuthAck()) && Connection_pb.AuthAck.toObject(includeInstance, f),
    ping: (f = msg.getPing()) && Connection_pb.Ping.toObject(includeInstance, f),
    pong: (f = msg.getPong()) && Connection_pb.Pong.toObject(includeInstance, f),
    disconnect: (f = msg.getDisconnect()) && Connection_pb.Disconnect.toObject(includeInstance, f),
    msgData: (f = msg.getMsgData()) && Msg_pb.MsgData.toObject(includeInstance, f),
    msgDataAck: (f = msg.getMsgDataAck()) && Msg_pb.MsgDataAck.toObject(includeInstance, f),
    createTeamReq: (f = msg.getCreateTeamReq()) && Team_pb.CreateTeamReq.toObject(includeInstance, f),
    dismissTeamReq: (f = msg.getDismissTeamReq()) && Team_pb.DismissTeamReq.toObject(includeInstance, f),
    queryMemberListReq: (f = msg.getQueryMemberListReq()) && Team_pb.QueryMemberListReq.toObject(includeInstance, f),
    joinTeamReq: (f = msg.getJoinTeamReq()) && Team_pb.JoinTeamReq.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Message;
  return proto.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMagic(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOpcode(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSeq(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPayloadlength(value);
      break;
    case 11:
      var value = new Connection_pb.Auth;
      reader.readMessage(value,Connection_pb.Auth.deserializeBinaryFromReader);
      msg.setAuth(value);
      break;
    case 12:
      var value = new Connection_pb.AuthAck;
      reader.readMessage(value,Connection_pb.AuthAck.deserializeBinaryFromReader);
      msg.setAuthAck(value);
      break;
    case 13:
      var value = new Connection_pb.Ping;
      reader.readMessage(value,Connection_pb.Ping.deserializeBinaryFromReader);
      msg.setPing(value);
      break;
    case 14:
      var value = new Connection_pb.Pong;
      reader.readMessage(value,Connection_pb.Pong.deserializeBinaryFromReader);
      msg.setPong(value);
      break;
    case 15:
      var value = new Connection_pb.Disconnect;
      reader.readMessage(value,Connection_pb.Disconnect.deserializeBinaryFromReader);
      msg.setDisconnect(value);
      break;
    case 21:
      var value = new Msg_pb.MsgData;
      reader.readMessage(value,Msg_pb.MsgData.deserializeBinaryFromReader);
      msg.setMsgData(value);
      break;
    case 22:
      var value = new Msg_pb.MsgDataAck;
      reader.readMessage(value,Msg_pb.MsgDataAck.deserializeBinaryFromReader);
      msg.setMsgDataAck(value);
      break;
    case 51:
      var value = new Team_pb.CreateTeamReq;
      reader.readMessage(value,Team_pb.CreateTeamReq.deserializeBinaryFromReader);
      msg.setCreateTeamReq(value);
      break;
    case 52:
      var value = new Team_pb.DismissTeamReq;
      reader.readMessage(value,Team_pb.DismissTeamReq.deserializeBinaryFromReader);
      msg.setDismissTeamReq(value);
      break;
    case 53:
      var value = new Team_pb.QueryMemberListReq;
      reader.readMessage(value,Team_pb.QueryMemberListReq.deserializeBinaryFromReader);
      msg.setQueryMemberListReq(value);
      break;
    case 54:
      var value = new Team_pb.JoinTeamReq;
      reader.readMessage(value,Team_pb.JoinTeamReq.deserializeBinaryFromReader);
      msg.setJoinTeamReq(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMagic();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getOpcode();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getSeq();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getPayloadlength();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getAuth();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      Connection_pb.Auth.serializeBinaryToWriter
    );
  }
  f = message.getAuthAck();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      Connection_pb.AuthAck.serializeBinaryToWriter
    );
  }
  f = message.getPing();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      Connection_pb.Ping.serializeBinaryToWriter
    );
  }
  f = message.getPong();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      Connection_pb.Pong.serializeBinaryToWriter
    );
  }
  f = message.getDisconnect();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      Connection_pb.Disconnect.serializeBinaryToWriter
    );
  }
  f = message.getMsgData();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      Msg_pb.MsgData.serializeBinaryToWriter
    );
  }
  f = message.getMsgDataAck();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      Msg_pb.MsgDataAck.serializeBinaryToWriter
    );
  }
  f = message.getCreateTeamReq();
  if (f != null) {
    writer.writeMessage(
      51,
      f,
      Team_pb.CreateTeamReq.serializeBinaryToWriter
    );
  }
  f = message.getDismissTeamReq();
  if (f != null) {
    writer.writeMessage(
      52,
      f,
      Team_pb.DismissTeamReq.serializeBinaryToWriter
    );
  }
  f = message.getQueryMemberListReq();
  if (f != null) {
    writer.writeMessage(
      53,
      f,
      Team_pb.QueryMemberListReq.serializeBinaryToWriter
    );
  }
  f = message.getJoinTeamReq();
  if (f != null) {
    writer.writeMessage(
      54,
      f,
      Team_pb.JoinTeamReq.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 magic = 1;
 * @return {number}
 */
proto.Message.prototype.getMagic = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setMagic = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 version = 2;
 * @return {number}
 */
proto.Message.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 opCode = 3;
 * @return {number}
 */
proto.Message.prototype.getOpcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setOpcode = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 seq = 4;
 * @return {number}
 */
proto.Message.prototype.getSeq = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setSeq = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 payloadLength = 5;
 * @return {number}
 */
proto.Message.prototype.getPayloadlength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.setPayloadlength = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional Auth auth = 11;
 * @return {?proto.Auth}
 */
proto.Message.prototype.getAuth = function() {
  return /** @type{?proto.Auth} */ (
    jspb.Message.getWrapperField(this, Connection_pb.Auth, 11));
};


/**
 * @param {?proto.Auth|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setAuth = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearAuth = function() {
  return this.setAuth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasAuth = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional AuthAck auth_ack = 12;
 * @return {?proto.AuthAck}
 */
proto.Message.prototype.getAuthAck = function() {
  return /** @type{?proto.AuthAck} */ (
    jspb.Message.getWrapperField(this, Connection_pb.AuthAck, 12));
};


/**
 * @param {?proto.AuthAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setAuthAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearAuthAck = function() {
  return this.setAuthAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasAuthAck = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional Ping ping = 13;
 * @return {?proto.Ping}
 */
proto.Message.prototype.getPing = function() {
  return /** @type{?proto.Ping} */ (
    jspb.Message.getWrapperField(this, Connection_pb.Ping, 13));
};


/**
 * @param {?proto.Ping|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setPing = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearPing = function() {
  return this.setPing(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasPing = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional Pong pong = 14;
 * @return {?proto.Pong}
 */
proto.Message.prototype.getPong = function() {
  return /** @type{?proto.Pong} */ (
    jspb.Message.getWrapperField(this, Connection_pb.Pong, 14));
};


/**
 * @param {?proto.Pong|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setPong = function(value) {
  return jspb.Message.setOneofWrapperField(this, 14, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearPong = function() {
  return this.setPong(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasPong = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional Disconnect disconnect = 15;
 * @return {?proto.Disconnect}
 */
proto.Message.prototype.getDisconnect = function() {
  return /** @type{?proto.Disconnect} */ (
    jspb.Message.getWrapperField(this, Connection_pb.Disconnect, 15));
};


/**
 * @param {?proto.Disconnect|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setDisconnect = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearDisconnect = function() {
  return this.setDisconnect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasDisconnect = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional MsgData msg_data = 21;
 * @return {?proto.MsgData}
 */
proto.Message.prototype.getMsgData = function() {
  return /** @type{?proto.MsgData} */ (
    jspb.Message.getWrapperField(this, Msg_pb.MsgData, 21));
};


/**
 * @param {?proto.MsgData|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setMsgData = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearMsgData = function() {
  return this.setMsgData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasMsgData = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional MsgDataAck msg_data_ack = 22;
 * @return {?proto.MsgDataAck}
 */
proto.Message.prototype.getMsgDataAck = function() {
  return /** @type{?proto.MsgDataAck} */ (
    jspb.Message.getWrapperField(this, Msg_pb.MsgDataAck, 22));
};


/**
 * @param {?proto.MsgDataAck|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setMsgDataAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearMsgDataAck = function() {
  return this.setMsgDataAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasMsgDataAck = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional CreateTeamReq create_team_req = 51;
 * @return {?proto.CreateTeamReq}
 */
proto.Message.prototype.getCreateTeamReq = function() {
  return /** @type{?proto.CreateTeamReq} */ (
    jspb.Message.getWrapperField(this, Team_pb.CreateTeamReq, 51));
};


/**
 * @param {?proto.CreateTeamReq|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setCreateTeamReq = function(value) {
  return jspb.Message.setOneofWrapperField(this, 51, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearCreateTeamReq = function() {
  return this.setCreateTeamReq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasCreateTeamReq = function() {
  return jspb.Message.getField(this, 51) != null;
};


/**
 * optional DismissTeamReq dismiss_team_req = 52;
 * @return {?proto.DismissTeamReq}
 */
proto.Message.prototype.getDismissTeamReq = function() {
  return /** @type{?proto.DismissTeamReq} */ (
    jspb.Message.getWrapperField(this, Team_pb.DismissTeamReq, 52));
};


/**
 * @param {?proto.DismissTeamReq|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setDismissTeamReq = function(value) {
  return jspb.Message.setOneofWrapperField(this, 52, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearDismissTeamReq = function() {
  return this.setDismissTeamReq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasDismissTeamReq = function() {
  return jspb.Message.getField(this, 52) != null;
};


/**
 * optional QueryMemberListReq query_member_list_req = 53;
 * @return {?proto.QueryMemberListReq}
 */
proto.Message.prototype.getQueryMemberListReq = function() {
  return /** @type{?proto.QueryMemberListReq} */ (
    jspb.Message.getWrapperField(this, Team_pb.QueryMemberListReq, 53));
};


/**
 * @param {?proto.QueryMemberListReq|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setQueryMemberListReq = function(value) {
  return jspb.Message.setOneofWrapperField(this, 53, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearQueryMemberListReq = function() {
  return this.setQueryMemberListReq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasQueryMemberListReq = function() {
  return jspb.Message.getField(this, 53) != null;
};


/**
 * optional JoinTeamReq join_team_req = 54;
 * @return {?proto.JoinTeamReq}
 */
proto.Message.prototype.getJoinTeamReq = function() {
  return /** @type{?proto.JoinTeamReq} */ (
    jspb.Message.getWrapperField(this, Team_pb.JoinTeamReq, 54));
};


/**
 * @param {?proto.JoinTeamReq|undefined} value
 * @return {!proto.Message} returns this
*/
proto.Message.prototype.setJoinTeamReq = function(value) {
  return jspb.Message.setOneofWrapperField(this, 54, proto.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Message} returns this
 */
proto.Message.prototype.clearJoinTeamReq = function() {
  return this.setJoinTeamReq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Message.prototype.hasJoinTeamReq = function() {
  return jspb.Message.getField(this, 54) != null;
};


goog.object.extend(exports, proto);
