// source: Msg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.MsgData', null, global);
goog.exportSymbol('proto.MsgDataAck', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MsgData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MsgData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MsgData.displayName = 'proto.MsgData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MsgDataAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MsgDataAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MsgDataAck.displayName = 'proto.MsgDataAck';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MsgData.prototype.toObject = function(opt_includeInstance) {
  return proto.MsgData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MsgData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MsgData.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    toId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    msgId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sessionType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    msgDirection: jspb.Message.getFieldWithDefault(msg, 6, 0),
    msgStatus: jspb.Message.getFieldWithDefault(msg, 7, 0),
    msgAttachstr: jspb.Message.getFieldWithDefault(msg, 8, ""),
    msgType: jspb.Message.getFieldWithDefault(msg, 9, 0),
    content: jspb.Message.getFieldWithDefault(msg, 10, ""),
    fromClientType: jspb.Message.getFieldWithDefault(msg, 11, 0),
    time: jspb.Message.getFieldWithDefault(msg, 12, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MsgData}
 */
proto.MsgData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MsgData;
  return proto.MsgData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MsgData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MsgData}
 */
proto.MsgData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFromId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setToId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsgId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSessionType(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMsgDirection(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMsgStatus(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsgAttachstr(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMsgType(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFromClientType(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MsgData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MsgData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MsgData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MsgData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getToId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMsgId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSessionType();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getMsgDirection();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getMsgStatus();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getMsgAttachstr();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getMsgType();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getFromClientType();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
};


/**
 * optional uint64 from_id = 1;
 * @return {number}
 */
proto.MsgData.prototype.getFromId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setFromId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string to_id = 2;
 * @return {string}
 */
proto.MsgData.prototype.getToId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setToId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string msg_id = 3;
 * @return {string}
 */
proto.MsgData.prototype.getMsgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setMsgId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 session_type = 4;
 * @return {number}
 */
proto.MsgData.prototype.getSessionType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setSessionType = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 msg_direction = 6;
 * @return {number}
 */
proto.MsgData.prototype.getMsgDirection = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setMsgDirection = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 msg_status = 7;
 * @return {number}
 */
proto.MsgData.prototype.getMsgStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setMsgStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string msg_attachStr = 8;
 * @return {string}
 */
proto.MsgData.prototype.getMsgAttachstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setMsgAttachstr = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional uint32 msg_type = 9;
 * @return {number}
 */
proto.MsgData.prototype.getMsgType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setMsgType = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string content = 10;
 * @return {string}
 */
proto.MsgData.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional uint32 from_client_type = 11;
 * @return {number}
 */
proto.MsgData.prototype.getFromClientType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setFromClientType = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint32 time = 12;
 * @return {number}
 */
proto.MsgData.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgData} returns this
 */
proto.MsgData.prototype.setTime = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MsgDataAck.prototype.toObject = function(opt_includeInstance) {
  return proto.MsgDataAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MsgDataAck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MsgDataAck.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    toId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sessionType: jspb.Message.getFieldWithDefault(msg, 3, 0),
    msgId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MsgDataAck}
 */
proto.MsgDataAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MsgDataAck;
  return proto.MsgDataAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MsgDataAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MsgDataAck}
 */
proto.MsgDataAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFromId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setToId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSessionType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsgId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MsgDataAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MsgDataAck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MsgDataAck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MsgDataAck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getToId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSessionType();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getMsgId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint64 from_id = 1;
 * @return {number}
 */
proto.MsgDataAck.prototype.getFromId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgDataAck} returns this
 */
proto.MsgDataAck.prototype.setFromId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string to_id = 2;
 * @return {string}
 */
proto.MsgDataAck.prototype.getToId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MsgDataAck} returns this
 */
proto.MsgDataAck.prototype.setToId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 session_type = 3;
 * @return {number}
 */
proto.MsgDataAck.prototype.getSessionType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.MsgDataAck} returns this
 */
proto.MsgDataAck.prototype.setSessionType = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string msg_id = 4;
 * @return {string}
 */
proto.MsgDataAck.prototype.getMsgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.MsgDataAck} returns this
 */
proto.MsgDataAck.prototype.setMsgId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto);
